# Generated by Django 5.2.7 on 2025-10-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detail_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
