# Generated by Django 5.2.7 on 2025-10-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('slug', models.SlugField(unique=True)),
                ('platform', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('teacher', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
